/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("org.eclipse.jgit:org.eclipse.jgit:6.8.0.202311291450-r")
    implementation("org.yaml:snakeyaml:2.2")
    implementation("com.github.javaparser:javaparser-core:3.25.8")
}

application {
    // Define the main class for the application.
    // mainClass.set("com.perseuspotter.ia.cmdapp")
    mainClass.set("com.perseuspotter.ia.JFXEntry")
}

javafx {
    version = "21.0.2"
    modules("javafx.controls")
}